// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/assets" | "/leaderboard" | "/me" | "/otfs/[slug]" | "/points" | "/privacy" | "/rules" | "/submit" | "/terms" | "/vote"
type AppRouteHandlerRoutes = "/api/auth/x" | "/api/auth/x/callback" | "/api/auth/x/disconnect" | "/api/health" | "/api/jobs/evidence" | "/api/jobs/markets" | "/api/jobs/prices" | "/api/v1/admin/export" | "/api/v1/admin/finalize" | "/api/v1/admin/proposals/[id]/moderate" | "/api/v1/assets" | "/api/v1/ballot" | "/api/v1/competition" | "/api/v1/launch-order" | "/api/v1/leaderboard" | "/api/v1/me" | "/api/v1/me/activity" | "/api/v1/points" | "/api/v1/proposals/[idOrSlug]" | "/api/v1/submissions" | "/api/v1/submissions/[id]/publish"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/auth/x": {}
  "/api/auth/x/callback": {}
  "/api/auth/x/disconnect": {}
  "/api/health": {}
  "/api/jobs/evidence": {}
  "/api/jobs/markets": {}
  "/api/jobs/prices": {}
  "/api/v1/admin/export": {}
  "/api/v1/admin/finalize": {}
  "/api/v1/admin/proposals/[id]/moderate": { "id": string; }
  "/api/v1/assets": {}
  "/api/v1/ballot": {}
  "/api/v1/competition": {}
  "/api/v1/launch-order": {}
  "/api/v1/leaderboard": {}
  "/api/v1/me": {}
  "/api/v1/me/activity": {}
  "/api/v1/points": {}
  "/api/v1/proposals/[idOrSlug]": { "idOrSlug": string; }
  "/api/v1/submissions": {}
  "/api/v1/submissions/[id]/publish": { "id": string; }
  "/assets": {}
  "/leaderboard": {}
  "/me": {}
  "/otfs/[slug]": { "slug": string; }
  "/points": {}
  "/privacy": {}
  "/rules": {}
  "/submit": {}
  "/terms": {}
  "/vote": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
