// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assets">> = Specific
  const handler = {} as typeof import("../../src/app/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/me/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/me">> = Specific
  const handler = {} as typeof import("../../src/app/me/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/otfs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/otfs/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/otfs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/points/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/points">> = Specific
  const handler = {} as typeof import("../../src/app/points/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rules">> = Specific
  const handler = {} as typeof import("../../src/app/rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/submit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/submit">> = Specific
  const handler = {} as typeof import("../../src/app/submit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/vote/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vote">> = Specific
  const handler = {} as typeof import("../../src/app/vote/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/x/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/x/callback">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/x/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/x/disconnect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/x/disconnect">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/x/disconnect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/x/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/x">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/x/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/evidence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/evidence">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/evidence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/markets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/markets">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/markets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/jobs/prices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/jobs/prices">> = Specific
  const handler = {} as typeof import("../../src/app/api/jobs/prices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/admin/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/export">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/admin/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/admin/finalize/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/finalize">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/admin/finalize/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/admin/proposals/[id]/moderate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/admin/proposals/[id]/moderate">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/admin/proposals/[id]/moderate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/assets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/assets">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/assets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/ballot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/ballot">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/ballot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/competition/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/competition">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/competition/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/launch-order/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/launch-order">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/launch-order/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/leaderboard">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/me/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/me/activity">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/me/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/points/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/points">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/points/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/proposals/[idOrSlug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/proposals/[idOrSlug]">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/proposals/[idOrSlug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/submissions/[id]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/submissions/[id]/publish">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/submissions/[id]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/v1/submissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/v1/submissions">> = Specific
  const handler = {} as typeof import("../../src/app/api/v1/submissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
