[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1
via_ir = true
bytecode_hash = "none"
extra_output = ["storageLayout"]

[profile.default.fuzz]
runs = 1_000

[profile.default.invariant]
runs = 128
depth = 64
fail_on_revert = false

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
