export const errorMessages: Record<string, string> = {
  X_NOT_VERIFIED: "A verified, public X account is required.",
  FOLLOWER_THRESHOLD: "Your X account does not meet the follower requirement.",
  ASSET_INELIGIBLE: "One or more portfolio assets are not currently eligible.",
  WEIGHTS_NOT_100: "Portfolio weights must total 100%.",
  X_RECONNECT_REQUIRED: "Sign in with X again so OTF Launch can refresh your eligibility.",
  X_POST_NOT_FOUND: "That public X post could not be found. Check the URL and try again.",
  PROOF_AUTHOR_MISMATCH: "This post was not published by your signed-in X account.",
  PROOF_CODE_MISSING: "The post does not contain the required verification code. Publish the prepared text without removing it.",
  PROOF_MISMATCH: "Paste a valid public x.com post URL.",
  CHALLENGE_EXPIRED: "This verification code expired. Prepare a new X post and try again.",
  X_RATE_LIMITED: "X is temporarily rate limited. Please try again shortly.",
  RATE_LIMITED: "Too many attempts. Please wait ten minutes and try again.",
  RATE_LIMIT_UNAVAILABLE: "Request protection is temporarily unavailable. Please try again shortly.",
  X_POST_CHANGED: "The required X post was deleted or changed, so the action is no longer valid.",
  POST_TOO_LONG: "The X post is too long. Shorten your context and try again.",
  DUPLICATE_VOTE: "You have already voted for this OTF.",
  SELF_VOTE: "You cannot vote for your own OTF.",
  ACTION_IN_PROGRESS: "This action is already being processed.",
  COMPETITION_NOT_OPEN: "The competition is not currently open."
};
