import { Callout, SectionCard } from "@/components/ui";
import Link from "next/link";

export const metadata = { title: "Competition rules" };
export default function RulesPage() { return <div className="pageShell contentPage"><header className="pageHeader"><h1>Competition rules</h1><p>A simple, auditable path from community proposal to main-app launch order.</p></header><SectionCard className="contentCard">
  <h2>Who can participate</h2><p>Anyone can browse. Submitting or voting requires a verified, public X account with at least 100 followers that is at least 30 days old. Eligibility is refreshed from the public profile whenever the account connects.</p>
  <h2>Submitting an OTF proposal</h2><ul><li>The first 7 days are reserved for submissions. Voting opens on competition day 8, and submissions remain open throughout the 30-day voting phase.</li><li>One OTF proposal per X account in the competition.</li><li>The name must end in “OTF”; tickers are uppercase and no longer than 16 characters.</li><li>Choose at least two registered 18-decimal assets and allocate at least 1% to each. An Open asset must pin an active Uniswap V3 asset/WETH market with a valid one-hour TWAP, and that pool must already have been at least seven days old when the competition started. <Link className="inlineLink" href="/rwas">View assets and markets</Link>.</li><li>Weights must total exactly 100%.</li><li>Add at least 20 characters of your own context, publish the prepared post from X, and paste its public URL for verification.</li><li>An OTF is Protocol-qualified only while every constituent is qualified. Any Open constituent makes the whole OTF Experimental. This OTF-level label is derived from the live constituent registry statuses—not permanently stored on the OTF—so it updates automatically after qualification, demotion, or blocking. Blocked assets cannot be submitted.</li><li>Acceptance requires a complete stored price checkpoint for every pinned source. CoinGecko indexing is not required for submission, votes, or launch rank.</li></ul>
  <h2 id="voting">Voting</h2><ul><li>Voting begins after the 7-day submission-only phase. Each eligible X account starts with 3 unlocked votes.</li><li>One additional vote unlocks every 3 voting days, up to 12 votes total. The final vote unlocks on voting day 27; no vote is added on day 30.</li><li>Unlocked votes may be cast across one or more OTF proposals. Creators may vote for any proposal, including their own.</li><li>Once cast, a vote cannot be moved, removed, or redistributed.</li><li>Every voting action requires a public X post. Several unlocked votes may be cast together and verified by one post.</li><li>OTF picks are omitted from each post by default and appear only when the voter chooses to reveal the OTFs and vote counts in that batch.</li><li>Every required voting post must remain public and unchanged. If one is deleted, protected, inaccessible, or materially edited, the entire ballot becomes invalid.</li><li>The voter and XP leaderboards use a stable generated alias by default. A voter’s real X username appears only after explicit, reversible authorization in their profile.</li></ul>
  <h2 id="ranking-and-launch-order">Ranking and launch order</h2><p>Votes from valid activated ballots count. Proposals sort by allocated votes descending, then earlier submission time, then immutable proposal ID. Ranks are unique ordinal positions.</p><Callout>The final ranking directly becomes main-app launch order: #1 first, #2 second, #3 third, and so on. Public pages show order only—not internal dates or readiness windows.</Callout>
  <h2>Moderation</h2><p>Manipulation, impersonation, automated abuse, deleted evidence posts, or invalid asset records may invalidate an action. Later fraud voids the affected slot; ranks are not renumbered.</p>
  <h2 id="live-xp">Live XP</h2><p>Exactly 10,000,000 XP is distributed: 3,500,000 participation, 3,500,000 qualified voter performance, 1,000,000 eligible experimental voter performance, 1,500,000 creator support, and 500,000 in fixed final creator awards. Pools use deterministic integer allocation. Live XP is provisional and can rise or fall until the final audit.</p>
  <h2>Performance XP</h2><p>Every verified vote batch creates a separate immutable tranche. Its cohort locks at the first complete eligible checkpoint and never backdates after a qualification change. Qualified tranches compare only with qualified OTFs; experimental tranches compare only with eligible experimental OTFs. Returns use stored onchain 24-hour V3 TWAP checkpoints—never market cap, FDV, or token supply.</p><p>Experimental performance requires every constituent to pass for seven continuous days: at least $30,000 pool liquidity, verified CoinGecko market cap of at least $100,000, a pool that was already at least seven days old when the competition started and has complete observations, GT verification and score of at least 60, no honeypot or critical sell/tax flag, at least 50% reported locked liquidity, and no more than 2% impact for a simulated $1,000 trade in either direction. Missing evidence is Pending, not a pass.</p>
  <h2>Participation and creator XP</h2><p>Participation uses valid vote units only and never follower count. Creator support uses the square root of unique valid non-self supporters. Proposals accepted before voting opens permanently receive the <strong>Submission Week Boost · 1.5×</strong> on creator score. The boost never changes votes, voter XP, launch ranking, or launch order.</p>
  <h2>Final XP</h2><p>Final creator ranks 1–10 receive 232,000, 120,000, 70,000, 30,000, 20,000, 12,000, 8,000, 5,000, 2,000, and 1,000 XP. Unawardable experimental performance rolls to qualified performance; if no performance scores exist it rolls to participation. Unused top-10 awards roll to creator support, preserving exactly 10,000,000 XP. The launch leaderboard and XP ledger remain separate immutable snapshots. <Link className="inlineLink" href="/points">View the XP ledger</Link>.</p><Callout tone="warning">Live or Final XP has no guaranteed monetary value. It is separate from launch ranking, which continues to use valid votes and the published tie-breakers only.</Callout>
  <h2>Changes</h2><p>The administrator may change or clarify these rules when needed, including after the competition opens. Material changes will be published here with their effective time and recorded in the audit history.</p>
</SectionCard></div>; }
