import { Callout, SectionCard } from "@/components/ui";
import Link from "next/link";

export const metadata = { title: "Competition rules" };
export default function RulesPage() { return <div className="pageShell contentPage"><header className="pageHeader"><h1>Competition rules</h1><p>A simple, auditable path from community proposal to main-app launch order.</p></header><SectionCard className="contentCard">
  <h2>Who can participate</h2><p>Anyone can browse. Submitting or voting requires a verified, public X account with at least 100 followers that is at least 30 days old. Eligibility is refreshed from the public profile whenever the account connects.</p>
  <h2>Submitting an OTF proposal</h2><ul><li>The first 7 days are reserved for submissions. Voting opens on competition day 8, and submissions remain open throughout the 30-day voting phase.</li><li>One OTF proposal per X account in the competition.</li><li>The name must end in “OTF”; tickers are uppercase and no longer than 16 characters.</li><li>Choose at least two supported Robinhood RWA assets and allocate at least 1% to each. <Link className="inlineLink" href="/rwas">View all supported RWAs</Link>.</li><li>Weights must total exactly 100%.</li><li>Add at least 20 characters of your own context, publish the prepared post from X, and paste its public URL for verification.</li></ul>
  <h2>Voting</h2><ul><li>Voting begins after the 7-day submission-only phase. Each eligible X account starts with 3 unlocked votes.</li><li>One additional vote unlocks every 3 voting days, up to 12 votes total. The final vote unlocks on voting day 27; no vote is added on day 30.</li><li>Unlocked votes may be cast across one or more OTF proposals. Creators may vote for any proposal, including their own.</li><li>Once cast, a vote cannot be moved, removed, or redistributed.</li><li>Every voting action requires a public X post. Several unlocked votes may be cast together and verified by one post.</li><li>OTF picks are omitted from each post by default and appear only when the voter chooses to reveal the OTFs and vote counts in that batch.</li><li>Every required voting post must remain public and unchanged. If one is deleted, protected, inaccessible, or materially edited, the entire ballot becomes invalid.</li></ul>
  <h2 id="ranking-and-launch-order">Ranking and launch order</h2><p>Votes from valid activated ballots count. Proposals sort by allocated votes descending, then earlier submission time, then immutable proposal ID. Ranks are unique ordinal positions.</p><Callout>The final ranking directly becomes main-app launch order: #1 first, #2 second, #3 third, and so on. Public pages show order only—not internal dates or readiness windows.</Callout>
  <h2>Moderation</h2><p>Manipulation, impersonation, automated abuse, deleted evidence posts, or invalid asset records may invalidate an action. Later fraud voids the affected slot; ranks are not renumbered.</p>
  <h2>Future rewards</h2><p>Verified activity is recorded so a methodology can be applied retroactively. No formula, balance, claim, monetary value, or guaranteed eligibility is announced in V1.</p>
  <h2>Changes</h2><p>The administrator may change or clarify these rules when needed, including after the competition opens. Material changes will be published here with their effective time and recorded in the audit history.</p>
</SectionCard></div>; }
