import { Callout, SectionCard } from "@/components/ui";
import Link from "next/link";

export const metadata = { title: "Competition rules" };
export default function RulesPage() { return <div className="pageShell contentPage"><header className="pageHeader"><h1>Competition rules</h1><p>A simple, auditable path from community proposal to main-app launch order.</p></header><SectionCard className="contentCard">
  <h2>Who can participate</h2><p>Anyone can browse. Creating an OTF or voting requires a verified, public X account with at least 100 followers that is at least 30 days old. Eligibility is refreshed from the public profile whenever the account connects.</p>
  <h2>Creating an OTF</h2><ul><li>The first 7 days are reserved for submissions. Voting opens on competition day 8, and submissions remain open throughout the 30-day voting phase.</li><li>Each X account may submit any number of OTF proposals. A submission may be deleted while it has 0 votes.</li><li>The name must end in “OTF”; tickers are uppercase and no longer than 16 characters.</li><li>Choose at least two distinct 18-decimal assets and allocate at least 1% to each. Directory records are reusable metadata only; they never authorize an asset or a price source. <Link className="inlineLink" href="/assets">View verified assets</Link>.</li><li>Unlisted assets are checked server-side through Robinhood RPC first. Their pool must be a canonical Uniswap V3 pool containing the asset and exactly canonical WETH or USDG, with a supported fee, initialization, at least 64 observations, and a successful one-hour observation. GeckoTerminal evidence must then show at least $30,000 liquidity, at least $100,000 verified market cap (never FDV), seven-day pool age, GT verification, GT score at least 50, no honeypot flag, and at least 50% locked liquidity.</li><li>For every constituent, supply and pin exactly one pricing route: direct Chainlink ASSET/USD, composed Chainlink ASSET/WETH × WETH/USD, or a Uniswap V3 asset/WETH or asset/USDG TWAP pool. Known configurations may be prefilled but remain editable. Uniswap V4 is not supported, and pricing never falls back automatically.</li><li>Weights must total exactly 100%.</li><li>Add your own optional context, publish the prepared post from X, and paste its public URL for verification.</li><li>An OTF is Verified only while every current constituent is verified; otherwise it is Non-verified. Verification selects the performance XP pool but never affects eligibility, pricing, fees, permissions, votes, or launch order.</li><li>Competition return snapshots come from external provider APIs and remain separate from the OTF&apos;s pinned onchain pricing. Missing competition prices make performance Pending but do not affect votes or launch rank.</li></ul>
  <h2 id="voting">Voting</h2><ul><li>Voting begins after the 7-day submission-only phase. Each eligible X account starts with 3 unlocked votes.</li><li>One additional vote unlocks every 3 voting days, up to 12 votes total. The final vote unlocks on voting day 27; no vote is added on day 30.</li><li>Unlocked votes may be cast across one or more OTF proposals. Creators may vote for any proposal, including their own.</li><li>Once cast, a vote cannot be moved, removed, redistributed, or made available again.</li><li>Every voting action requires a public X post. Several unlocked votes may be cast together and verified by one post.</li><li>OTF picks are omitted from each post by default and appear only when the voter chooses to reveal the OTFs and vote counts in that batch.</li><li>Every required voting post must remain public and unchanged, including after the competition ends. Deleting or editing a voting post is prohibited and never restores its spent vote slots.</li></ul>
  <h2 id="ranking-and-launch-order">Ranking and launch order</h2><p>Votes from valid activated ballots count. Proposals sort by allocated votes descending, then earlier submission time, then immutable proposal ID. Ranks are unique ordinal positions.</p><Callout>The final ranking directly becomes main-app launch order: #1 first, #2 second, #3 third, and so on. Public pages show order only—not internal dates or readiness windows.</Callout>
  <h2>Moderation</h2><p>Manipulation, impersonation, automated abuse, deleted evidence posts, or invalid asset records may invalidate an action. Later fraud voids the affected slot; ranks are not renumbered.</p>
  <h2 id="xp-allocation">XP allocation</h2><p>Exactly 10,000,000 XP will be allocated once, after the competition closes and the final audit is complete: 3,500,000 verified-performance XP, 1,750,000 non-verified-performance XP, 2,750,000 participation XP, and 2,000,000 creator XP. No provisional XP balance or ranking is calculated or published during the competition.</p>
  <h2>Performance XP</h2><p>Every verified vote batch creates a separate immutable tranche. Votes for Verified OTFs compete for the 3,500,000 XP verified-performance pool—a 100% boost over the 1,750,000 XP pool for Non-verified OTFs. Vote activation references the newest complete saved price checkpoint at or before activation; it never calls a provider. Market cap, FDV, and token supply never enter return calculations.</p>
  <h2>Participation and creator XP</h2><p>Participation uses valid vote units only and never follower count. The full 2,000,000 creator pool is divided among proposal creators in direct proportion to the valid votes their proposals receive.</p>
  <h2>Final allocation</h2><p>If either performance pool has no eligible score, that pool rolls to participation. After close, the OTF team exports the frozen competition inputs, calculates the final XP allocation outside the launch app, verifies the 10,000,000 XP total, and publishes the result. <Link className="inlineLink" href="/xp">View the allocation method</Link>.</p><Callout tone="warning">XP has no guaranteed monetary value. It is separate from launch ranking, which continues to use valid votes and the published tie-breakers only.</Callout>
  <h2>Changes</h2><p>The administrator may change or clarify these rules when needed, including after the competition opens. Material changes will be published here with their effective time and recorded in the audit history.</p>
</SectionCard></div>; }
